---
title: "Regression_symmetric_script"
author: "Hammed Akande"
date: "2024-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
pacman::p_load(tidyverse)

```

```{r}


# Create an empty list to store regression results for each metric
sym_regression_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[4:12]) { 
  regression_results <- data.frame(
    iteration = 1:30,
    coef = rep(NA, 30),
    r_squared = rep(NA, 30)
  )
  
  # Fit linear regression for each iteration
  for (i in 1:30) {
    lm_model <- lm(niche_breadth ~ result_df[result_df$iteration == i, col],
                   data = result_df[result_df$iteration == i, ])
    
    # Store coefficients and R-squared values
    regression_results$coef[i] <- coef(lm_model)[2]  
    regression_results$r_squared[i] <- summary(lm_model)$r.squared
  }
  
  # Store the regression results in the list
  sym_regression_results_list[[col]] <- regression_results
}

# Create an empty data frame to store the results
mean_sym_regression_results <- data.frame(
  metric = character(0),
  mean_coef = double(0),
  mean_r_squared = double(0)
)

# Loop through each metric
for (col in names(sym_regression_results_list)) {
  mean_coef <- mean(sym_regression_results_list[[col]]$coef, na.rm = TRUE)
  mean_r_squared <- mean(sym_regression_results_list[[col]]$r_squared, na.rm = TRUE)
  
  # Append results to the data frame
  mean_sym_regression_results <- rbind(mean_sym_regression_results,data.frame(metric = col, 
                                                  mean_coef = mean_coef,
                                                  mean_r_squared = mean_r_squared))
}




mean_sym_regression_results


```


```{r}

# Plot the mean R-squared values
ggplot(mean_sym_regression_results, aes(x = metric, y = mean_r_squared)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "R-squared values for each metric",
       x = "Metric",
       y = "R-squared") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1))


# Convert the list of data frames to a single data frame
sym_regression_df <- bind_rows(sym_regression_results_list, .id = "metric")

# Plot using ggplot2 with facets
ggplot(sym_regression_df, aes(x = iteration, y = r_squared)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ metric, scales = "free_y", ncol = 2) +
  labs(title = "R-squared values for each metric across iterations",
       x = "Iteration",
       y = "R-squared") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1)) 

```



```{r}

# Define a custom color palette 
custom_colors <- c("beta.a" = "#1f77b4",  # Blue
                   "beta.w" = "#ff7f0e",  # Orange
                   "hv_blond" = "#2ca02c",  # Green
                   "nb_dist" = "#d62728",  # Red
                   "nb_Gam" = "#9467bd",  # Purple
                   "nb_latent" = "#8c564b",  # Brown
                   "nr_hv" = "#e377c2",  # Pink
                   "om_tol" = "#7f7f7f",  # Gray
                   "SimpSSI" = "#bcbd22")  # Yellow-green

result_df_long <- result_df %>%
  pivot_longer(cols = 4:12, names_to = "Metrics", values_to = "values")

# Normalize the NicheBreadth values to a range of 0 to 1
result_df_long <- result_df_long %>%
  mutate(metrics_scaled = (values - min(values)) / (max(values) - min(values)))


# Jitter plot for niche breadth across iterations and metrics
ggplot(result_df_long, aes(x = factor(iteration), y = metrics_scaled, color = Metrics)) +
  geom_jitter(width = 0.2, height = 0, alpha=0.6, size=1.5) +
  labs(x = "Iterations", y = "Estimated Niche Breadth", title = "Niche Breadth Across Iterations and Metrics") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1))
  #scale_color_manual(values = custom_colors)




```


```{r}

# Box plot for niche breadth across iterations and metrics

ggplot(result_df_long, aes(x = factor(iteration), y = metrics_scaled, color = Metrics)) +
  geom_boxplot() +
  labs(x = "Iterations", y = "Estimated Niche Breadth", title = "Niche Breadth Across Iterations and Metrics") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1))


ggplot(result_df_long, aes(x = factor(iteration), y = metrics_scaled, fill = Metrics)) +
  geom_boxplot(alpha = 0.7, outlier.size = 1, outlier.shape = 16) +
  labs(x = "Iterations", y = "Estimated Niche Breadth", title = "Niche Breadth Across Iterations and Metrics") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap(~ Metrics, scales = "free_y")  # Facet by each metric




```


#Facet by metrics

```{r}

# Jitter plot for niche breadth across iterations and metrics
ggplot(result_df_long, aes(x = factor(iteration), y = metrics_scaled, color = Metrics)) +
  geom_jitter(width = 0.2, height = 0, alpha=0.6, size=1.5) +
  facet_wrap(~ Metrics, scales = "free_y") +
  labs(x = "Iterations", y = "Estimated Niche Breadth", title = "Niche Breadth Across Iterations and Metrics") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1))


```





```{r}


# Create a list to store the ggplot objects
sym_plot_list_reg <- list()

# Create a scatter plot for each metric and store it in the plot_list
for (metric_name in names(sym_regression_results_list)) {
  plot_reg <- ggplot(sym_regression_results_list[[metric_name]], aes(x = iteration, y = r_squared)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = paste("Scatter Plot for", metric_name),
         x = "Iteration",
         y = "R-squared") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1)) 
  
  sym_plot_list_reg[[metric_name]] <- plot_reg
}

# Display the plots
for (i in seq_along(sym_plot_list_reg)) {
  print(sym_plot_list_reg[[i]])
}

```




#ANOVA across iterations

```{r}


# Create an empty list to store R-squared, ANOVA results, and plots for each metric
sym_anova_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[4:12]) {  
  sym_anova_results <- data.frame(
    iteration = 1:30,
    r_squared = rep(NA, 30),
    anova_f_value = rep(NA, 30),
    anova_p_value = rep(NA, 30)
  )
  
  # Calculate R-squared, ANOVA F-value, and ANOVA p-value for each iteration
  for (i in 1:30) {
    sym_lm <- lm(niche_breadth ~ result_df[result_df$iteration == i, col],
                 data = result_df[result_df$iteration == i, ])
    sym_anova_results$r_squared[i] <- summary(sym_lm)$r.squared
    
    # Calculate ANOVA
    anova_result <- anova(sym_lm)
    sym_anova_results$anova_f_value[i] <- anova_result[, "F value"][1]
    sym_anova_results$anova_p_value[i] <- anova_result[, "Pr(>F)"][1]
  }
  
  # Store the results in the list
  sym_anova_results_list[[col]] <- sym_anova_results
}

# Calculate the mean R-squared, mean ANOVA F-value, and mean ANOVA p-value for each metric
sym_anova_mean_results <- data.frame(
  metric = character(0),
  sym_anova_mean_r_squared = double(0),
  sym_mean_anova_f_value = double(0),
  sym_mean_anova_p_value = double(0)
)

for (col in names(sym_anova_results_list)) {
  sym_anova_mean_r_squared <- mean(sym_anova_results_list[[col]]$r_squared, na.rm = TRUE)
  sym_mean_anova_f_value <- mean(sym_anova_results_list[[col]]$anova_f_value, na.rm = TRUE)
  sym_mean_anova_p_value <- mean(sym_anova_results_list[[col]]$anova_p_value, na.rm = TRUE)
  
  sym_anova_mean_results <- rbind(sym_anova_mean_results, data.frame(metric = col, 
                                                          sym_anova_mean_r_squared = sym_anova_mean_r_squared, 
                                                          sym_mean_anova_f_value = sym_mean_anova_f_value,
                                                          sym_mean_anova_p_value = sym_mean_anova_p_value))
}

sym_anova_mean_results


```


```{r}


#Export the results to a csv file

write.csv(sym_anova_mean_results, file = "uniform_sym_anova_mean_results.csv")





```



```{r}


# Create a list to store the ggplot objects
sym_plot_list_reg_anova <- list()

# Create a scatter plot for each metric and store it in the plot_list
for (metric_name in names(sym_anova_results_list)) {
  plot_reg_anova <- ggplot(sym_anova_results_list[[metric_name]], aes(x = iteration, y = r_squared)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = paste("Scatter Plot for", metric_name),
         x = "Iteration",
         y = "R-squared") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1))
  
  sym_plot_list_reg_anova[[metric_name]] <- plot_reg_anova
}

# Display the plots
for (i in seq_along(sym_plot_list_reg_anova)) {
  print(sym_plot_list_reg_anova[[i]])
}

```






