---
title: "Regression_symmetric_script"
author: "Hammed Akande"
date: "2024-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}


# Create an empty list to store regression results for each metric
sym_regression_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[4:12]) { 
  regression_results <- data.frame(
    iteration = 1:30,
    coef = rep(NA, 30),
    r_squared = rep(NA, 30)
  )
  
  # Fit linear regression for each iteration
  for (i in 1:30) {
    lm_model <- lm(niche_breadth ~ result_df[result_df$iteration == i, col],
                   data = result_df[result_df$iteration == i, ])
    
    # Store coefficients and R-squared values
    regression_results$coef[i] <- coef(lm_model)[2]  
    regression_results$r_squared[i] <- summary(lm_model)$r.squared
  }
  
  # Store the regression results in the list
  sym_regression_results_list[[col]] <- regression_results
}

# Create an empty data frame to store the results
mean_sym_regression_results <- data.frame(
  metric = character(0),
  mean_coef = double(0),
  mean_r_squared = double(0)
)

# Loop through each metric
for (col in names(sym_regression_results_list)) {
  mean_coef <- mean(sym_regression_results_list[[col]]$coef, na.rm = TRUE)
  mean_r_squared <- mean(sym_regression_results_list[[col]]$r_squared, na.rm = TRUE)
  
  # Append results to the data frame
  mean_sym_regression_results <- rbind(mean_sym_regression_results,data.frame(metric = col, 
                                                  mean_coef = mean_coef,
                                                  mean_r_squared = mean_r_squared))
}




mean_sym_regression_results


```


```{r}

# Plot the mean R-squared values
ggplot(mean_sym_regression_results, aes(x = metric, y = mean_r_squared)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "R-squared values for each metric",
       x = "Metric",
       y = "R-squared") +
  theme_minimal()


# Convert the list of data frames to a single data frame
sym_regression_df <- bind_rows(sym_regression_results_list, .id = "metric")

# Plot using ggplot2 with facets
(R_sq_all_iterations <- ggplot(sym_regression_df, aes(x = iteration, y = r_squared)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ metric, scales = "free_y", ncol = 2) +
  labs(title = "R-squared values for each metric across iterations",
       x = "Iteration",
       y = "R-squared") +
  theme_minimal())

```


```{r}

#save the plot as image

ggsave("R_sq_all_iterations.png", R_sq_all_iterations, height = 10, width = 10, units = "in", dpi = 300)

```


```{r}


# Create a list to store the ggplot objects
sym_plot_list_reg <- list()

# Create a scatter plot for each metric and store it in the plot_list
for (metric_name in names(sym_regression_results_list)) {
  plot_reg <- ggplot(sym_regression_results_list[[metric_name]], aes(x = iteration, y = r_squared)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = paste("Scatter Plot for", metric_name),
         x = "Iteration",
         y = "R-squared") +
    theme_minimal()
  
  sym_plot_list_reg[[metric_name]] <- plot_reg
}

# Display the plots
for (i in seq_along(sym_plot_list_reg)) {
  print(sym_plot_list_reg[[i]])
}

```




#ANOVA across iterations

```{r}


# Create an empty list to store R-squared, ANOVA results, and plots for each metric
sym_anova_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[4:12]) {  
  sym_anova_results <- data.frame(
    iteration = 1:30,
    r_squared = rep(NA, 30),
    anova_f_value = rep(NA, 30),
    anova_p_value = rep(NA, 30)
  )
  
  # Calculate R-squared, ANOVA F-value, and ANOVA p-value for each iteration
  for (i in 1:30) {
    sym_lm <- lm(niche_breadth ~ result_df[result_df$iteration == i, col],
                 data = result_df[result_df$iteration == i, ])
    sym_anova_results$r_squared[i] <- summary(sym_lm)$r.squared
    
    # Calculate ANOVA
    anova_result <- anova(sym_lm)
    sym_anova_results$anova_f_value[i] <- anova_result[, "F value"][1]
    sym_anova_results$anova_p_value[i] <- anova_result[, "Pr(>F)"][1]
  }
  
  # Store the results in the list
  sym_anova_results_list[[col]] <- sym_anova_results
}

# Calculate the mean R-squared, mean ANOVA F-value, and mean ANOVA p-value for each metric
sym_anova_mean_results <- data.frame(
  metric = character(0),
  sym_anova_mean_r_squared = double(0),
  sym_mean_anova_f_value = double(0),
  sym_mean_anova_p_value = double(0)
)

for (col in names(sym_anova_results_list)) {
  sym_anova_mean_r_squared <- mean(sym_anova_results_list[[col]]$r_squared, na.rm = TRUE)
  sym_mean_anova_f_value <- mean(sym_anova_results_list[[col]]$anova_f_value, na.rm = TRUE)
  sym_mean_anova_p_value <- mean(sym_anova_results_list[[col]]$anova_p_value, na.rm = TRUE)
  
  sym_anova_mean_results <- rbind(sym_anova_mean_results, data.frame(metric = col, 
                                                          sym_anova_mean_r_squared = sym_anova_mean_r_squared, 
                                                          sym_mean_anova_f_value = sym_mean_anova_f_value,
                                                          sym_mean_anova_p_value = sym_mean_anova_p_value))
}

sym_anova_mean_results


```


```{r}


#Export the result
write.csv(sym_anova_mean_results, file = "single_uniform_sym_anova_mean_results.csv")

```



```{r}


# Create a list to store the ggplot objects
sym_plot_list_reg_anova <- list()

# Create a scatter plot for each metric and store it in the plot_list
for (metric_name in names(sym_anova_results_list)) {
  plot_reg_anova <- ggplot(sym_anova_results_list[[metric_name]], aes(x = iteration, y = r_squared)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = paste("Scatter Plot for", metric_name),
         x = "Iteration",
         y = "R-squared") +
    theme_minimal()
  
  sym_plot_list_reg_anova[[metric_name]] <- plot_reg_anova
}

# Display the plots
for (i in seq_along(sym_plot_list_reg_anova)) {
  print(sym_plot_list_reg_anova[[i]])
}

```







#Plot them side by side using Heat Map

```{r}

# Function to create heatmap
create_heatmap <- function(regression_list, title, exclude_metric = NULL) {
  # Reshape data for plotting
  reg_melted <- do.call(rbind, lapply(seq_along(regression_list), function(i) {
    data <- regression_list[[i]]
    data$metric <- names(regression_list)[i]
    return(data)
  }))
  
  # Exclude niche_breadth
  if (!is.null(exclude_metric)) {
    reg_melted <- reg_melted[reg_melted$metric != exclude_metric, ]
  }
  
  
  # Create heatmap
  ggplot(reg_melted, aes(x = iteration, y = metric, fill = r_squared)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1, 1), space = "Lab", name = expression(R^2)) +
    theme_minimal() +
    labs(title = title,
         x = "Iterations",
         y = "Metrics") +
    theme(plot.title = element_text(hjust = 0.5))
}



# Plot symmetric and asymmetric heatmaps side by side
(single_heatmap <- gridExtra::grid.arrange(
  create_heatmap(sym_regression_results_list, title = "Symmetric"),
  create_heatmap(asy_regression_results_list, title = "Asymmetric"),
  #create_heatmap(correlation_results_list, "Symmetric"),
  #create_heatmap(correlation_results_list, "Asymmetric"),
  ncol = 2
))



```



```{r}


#save the plot as image

ggsave("single2_heatmap.png", single_heatmap, height = 10, width = 10, units = "in", dpi = 300)

```


