---
title: "Sp_simulation_ch1"
author: "Hammed Akande"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}


source("AllNicheBreadthFunctions_Hmd.R")
source("Symmetric_Gaussian_functions.R")
source("AsymetricGaussian_functions.R")
source("random_scenario_function.R")
source("DavidZelenyThetaFunctions.R")

#load all the packages needed to run this script
if (!require("pacman")) install.packages("pacman")
pacman::p_load(stars,sf,data.table,ade4,tidyverse,cubelyr,tmap,mapview,exactextractr,lubridate,prism,e1071,vegan,dplyr,reshape2,ggpmisc,ggplot2,e1071,corrplot,nicheROVER,hypervolume,ade4,ggpubr,mFD,ecoCopula)


```


```{r}

# define params
reps <- 30  # do 30 iterations.
n.species <- 30 #number of species
n.communities <- 500 #number of sites


```



#Symmetric distribution


```{r}


#This can take time to run
start <- Sys.time()

# Initialize an empty data frame to store results
result_df <- data.frame(iteration = integer(0), sci.name = character(0), niche_b = numeric(0),
                        SimpSSI = numeric(0),beta.a = numeric(0),beta.w = numeric(0),om_result = numeric(0),
                        levins = numeric(0),nicheRover_hyp_m = numeric(0),
                        hyp_nb_df = numeric(0),nicheBreadth_Gam = numeric(0),
                        nicheBreadth_Gam.latents = numeric(0),nicheBreadth_avg.Dist = numeric(0))

for (iteration in 1:reps) {
  
  

  # Generate the community with new niche_breadth values

  simul.com <- generate_community.Symmetric.Gaussian.multi.x(n.species=30,n.sites=500,n.x=2,
                                                           shape = 0.1,rate=0.5)
  
  sim.com <- simul.com$community_abundance_matrix
  
  # Transform to presence-absence
  sim.com[sim.com > 0] <- 1
  colnames(sim.com) <- paste0("sp", 1:n.species)
  
  # Generate niche_breadth values
  niche.breadth <- simul.com$breadth.Oracle
  names(niche.breadth) <- paste0("sp", 1:n.species)
  
  #Store environmental variables
  env_vars <- simul.com$x
  colnames(env_vars) <- c("env.1", "env.2")
  env_vars <- as.data.frame(env_vars)
  env.1 <- env_vars$env.1
  env.2 <- env_vars$env.2



  # Calculate omi parameters and om_tol
  SimpSSI <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$multi.sim
  beta.a <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$Beta.a
  beta.w <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$Beta.w
  omi_result <- omi_params_fun(env_vars = data.frame(env.1, env.2), PA = sim.com)
  levins <- Levins(as.data.frame(t(sim.com))[, 1:500] %>% setNames(paste0("sites", 1:nrow(sim.com))))
  nicheRover_hyp_m <- nr_hypervolume_fun(sim.com, env_vars, nsamples = 1000)
  hyp_nb_df <- hypervolume_blond_fun(sim.com, env_vars)
  nicheBreadth_Gam <- estimate_nicheBreadth_Gam(sim.com, env_vars)
  nicheBreadth_Gam.latents <- estimate_nicheBreadth_Latents(sim.com, env_vars,nlv=5)
  nicheBreadth_avg.Dist <- estimate_nicheBreadth_avg.Dist(sim.com, env_vars)



  # Append the results to the result_df
  result_df <- rbind(result_df, data.frame(iteration, omi_result$sci.name, niche.breadth,SimpSSI,
                                           beta.a,beta.w,omi_result$om_tol,
                                           levins$Levins,nicheRover_hyp_m$nr_hypervolume,
                                           hyp_nb_df$hypervolume,nicheBreadth_Gam$Niche_Breadth,
                                           nicheBreadth_Gam.latents,nicheBreadth_avg.Dist))
}

end <- Sys.time()
end-start

# Calculate the mean for all metrics for each sci.name
colnames(result_df) <- c("iteration", "sci.name","niche_breadth","SimpSSI", "beta.a", "beta.w", "om_tol",
                         "levins","nr_hv","hv_blond","nb_Gam", "nb_latent", "nb_dist")

# Calculate the correlation between niche_b and all the metrics for every iteration
# Create an empty list to store correlation results for each metric
correlation_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[-c(1, 2)]) {
  correlation_results <- data.frame(
    iteration = 1:reps,
    correlation = rep(NA, reps)
  )
  
  # Calculate correlation for each iteration
  for (i in 1:reps) {
    correlation <- cor(result_df[result_df$iteration == i, "niche_breadth"],
                       result_df[result_df$iteration == i, col],
                       method = "spearman")
    correlation_results$correlation[i] <- correlation
  }
  
  # Store the correlation results in the list
  correlation_results_list[[col]] <- correlation_results
}


# Calculate the mean correlation for each metric
mean_correlation_results <- data.frame(
  metric = character(0),
  mean_correlation = double(0)
)

for (col in names(correlation_results_list)) {
  mean_corr <- mean(correlation_results_list[[col]]$correlation, na.rm = TRUE)
  mean_correlation_results <- rbind(mean_correlation_results, data.frame(metric = col, mean_correlation = mean_corr))
}


#Sym_correlation_results <- mean_correlation_results

# Loop through and print the correlation results for each metric 
#for (col in names(correlation_results_list)) {
#  print(paste("Metric:", col))
#  print(correlation_results_list[[col]])
#}


#save.image("Symmetric_Gaussian_model.RData")

#load("Symmetric_Gaussian_model.RData")


```




#Using Asymetric Gausian


```{r}


#This can take time to run
start <- Sys.time()

# Initialize an empty data frame to store results
result_df <- data.frame(iteration = integer(0), sci.name = character(0), niche_b = numeric(0),
                        SimpSSI = numeric(0),beta.a = numeric(0),beta.w = numeric(0),om_result = numeric(0),
                        levins = numeric(0),nicheRover_hyp_m = numeric(0),
                        hyp_nb_df = numeric(0),nicheBreadth_Gam = numeric(0),
                        nicheBreadth_Gam.latents = numeric(0),nicheBreadth_avg.Dist = numeric(0))

for (iteration in 1:reps) {
  
  

  # Generate the community with new niche_breadth values

  simulated.com <- generate_community.Asymetric.Gaussian.multi.x(n.species=30,n.sites=500,n.x=2,
                                                           shape = 0.1,rate=0.5)
  
  sim.com <- simulated.com$community_abundance_matrix
  
  # Transform to presence-absence
  sim.com[sim.com > 0] <- 1
  colnames(sim.com) <- paste0("sp", 1:n.species)
  
  # Generate niche_breadth values
  niche.breadth <- simulated.com$breadth.Oracle
  names(niche.breadth) <- paste0("sp", 1:n.species)
  #nb <- as.data.frame(niche.breadth)
  #nb$species <- row.names(nb)
  #env_vars <- cbind(env.1, env.2)
  env_vars <- simulated.com$x
  colnames(env_vars) <- c("env.1", "env.2")
  env_vars <- as.data.frame(env_vars)
  env.1 <- env_vars$env.1
  env.2 <- env_vars$env.2



  # Calculate omi parameters and om_tol
  SimpSSI <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$multi.sim
  beta.a <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$Beta.a
  beta.w <- co_occur(GOSmat, reps = 100, psample = 4, psample2 = 2)$Beta.w
  omi_result <- omi_params_fun(env_vars = data.frame(env.1, env.2), PA = sim.com)
  levins <- Levins(as.data.frame(t(sim.com))[, 1:500] %>% setNames(paste0("sites", 1:nrow(sim.com))))
  nicheRover_hyp_m <- nr_hypervolume_fun(sim.com, env_vars, nsamples = 1000)
  hyp_nb_df <- hypervolume_blond_fun(sim.com, env_vars)
  nicheBreadth_Gam <- estimate_nicheBreadth_Gam(sim.com, env_vars)
  nicheBreadth_Gam.latents <- estimate_nicheBreadth_Latents(sim.com, env_vars,nlv=5)
  nicheBreadth_avg.Dist <- estimate_nicheBreadth_avg.Dist(sim.com, env_vars)



  # Append the results to the result_df
  result_df <- rbind(result_df, data.frame(iteration, omi_result$sci.name, niche.breadth,SimpSSI,
                                           beta.a,beta.w,omi_result$om_tol,
                                           levins$Levins,nicheRover_hyp_m$nr_hypervolume,
                                           hyp_nb_df$hypervolume,nicheBreadth_Gam$Niche_Breadth,
                                           nicheBreadth_Gam.latents,nicheBreadth_avg.Dist))
}

end <- Sys.time()
end-start

# Calculate the mean for all metrics for each sci.name
colnames(result_df) <- c("iteration", "sci.name","niche_breadth","SimpSSI", "beta.a", "beta.w", "om_tol","levins","nr_hv","hv_blond","nb_Gam", "nb_latent", "nb_dist")


# Calculate the correlation between niche_b and all the metrics for every iteration

# Create an empty list to store correlation results for each metric
correlation_results_list <- list()

# Loop through each metric
for (col in colnames(result_df)[-c(1, 2)]) {
  correlation_results <- data.frame(
    iteration = 1:reps,
    correlation = rep(NA, reps)
  )
  
  # Calculate correlation for each iteration
  for (i in 1:reps) {
    correlation <- cor(result_df[result_df$iteration == i, "niche_breadth"],
                       result_df[result_df$iteration == i, col],
                       method = "spearman")
    correlation_results$correlation[i] <- correlation
  }
  
  # Store the correlation results in the list
  correlation_results_list[[col]] <- correlation_results
}


# Calculate the mean correlation for each metric
mean_correlation_results <- data.frame(
  metric = character(0),
  mean_correlation = double(0)
)

for (col in names(correlation_results_list)) {
  mean_corr <- mean(correlation_results_list[[col]]$correlation, na.rm = TRUE)
  mean_correlation_results <- rbind(mean_correlation_results, data.frame(metric = col, mean_correlation = mean_corr))
}



# Loop through and print the correlation results for each metric 
#for (col in names(correlation_results_list)) {
#  print(paste("Metric:", col))
#  print(correlation_results_list[[col]])
#}

#Asym_correlation_results <- mean_correlation_results

#save.image("Asymmetric_Gaussian_model.RData")

#load("Asymmetric_Gaussian_model.RData")


```



```{r}



community_data <- generate_random_community(n.species = 30, n.sites = 500, n.x = 2, shape = 0.1, rate = 0.5)


com_pa <- community_data$community_abundance_matrix
  
# Transform to presence-absence
com_pa[com_pa > 0] <- 1
#colnames(com_pa) <- paste0("sp", 1:n.species)

br <- community_data$breadth.Oracle  
en <- community_data$x
en <- as.data.frame(en)
hist(en$V2)

hist(apply(com_pa,2,sum))

colSums(com_pa)


```



#plot the two scenarios

```{r}


data1 = Sym_correlation_results[-1,] #remove niche_b
data2 = Asym_correlation_results[-1,]


data1$group <- "Symmetric"
data2$group <- "Asymmetric"
combined_data <- rbind(data1, data2)

#barplot
ggplot(combined_data, aes(x = metric, y = mean_correlation, fill = group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Comparison of Mean Correlation for Metrics",
       x = "Metric",
       y = "Mean Correlation") +
  theme_minimal() +
  scale_fill_manual(values = c("Symmetric" = "green", "Asymmetric" = "purple"))






```




```{r}


mean_metric_plot <- ggplot(combined_data, aes(x = metric, y = mean_correlation, fill = group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Comparison of Mean Correlation for Metrics",
       x = "Metric",
       y = "Mean Correlation") +
  theme_minimal() +
  scale_fill_manual(values = c("Symmetric" = "green", "Asymmetric" = "purple"))

output_file_path <- "path/to/your/output/file/my_plot.jpg"

ggsave("mean_metric_plot.jpg", plot = mean_metric_plot, device = "jpeg", width = 6, height = 4, units = "in")



```




